import { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import styles from './test-index.module.css';

export const getStaticProps = async () => {
  const res = await fetch(
    `https://api.themoviedb.org/3/trending/movie/week?api_key=${process.env.TMDB_API_KEY}`
  );

  const data = await res.json();

  return {
    props: {
      popularMovies: data.results,
    },
  };
};

interface Props {
  popularMovies: [];
}

const TestHome: NextPage<Props> = ({ popularMovies }) => {
  return (
    <>
      <Head>
        <title>Main page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.container}>
        {popularMovies.map(
          ({
            id,
            poster_path,
            title,
          }: {
            id: number;
            poster_path: string;
            title: string;
          }) => (
            <div key={id}>
              <Image
                alt={title}
                height={240}
                src={`https://image.tmdb.org/t/p/original${poster_path}`}
                width={240}
              />
              <h1>{title}</h1>
            </div>
          )
        )}
      </main>
    </>
  );
};

export default TestHome;
