name: deploy sep-6-client to vercel

on:
  pull_request:
    branches:
      - main

jobs:
  vercel:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      #add env file to .env.local
      - name: Set Env Vars on Vercel Project
        uses: dkershner6/vercel-set-env-action@v1
        with:
          token: ${{ secrets.VERCEL_TOKEN }}
          projectName: sep-6 # project name in Vercel
          envVariableKeys: TMDB_API_KEY
        env:
          TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}
          TARGET_TMDB_API_KEY: preview,development,production
          TYPE_TMDB_API_KEY: encrypted

      # deploy app to vercel
      - name: deploy site to vercel
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }} # Required
          vercel-args: '--prod' #Optional
          vercel-org-id: ${{ secrets.ORG_ID}} #Required
          vercel-project-id: ${{ secrets.PROJECT_ID}} #Required
